apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: prod
spec:
  ports:
    - name: web
      port: 9000
      targetPort: 9000  
      nodePort: 30090            
  selector:
    app: backend
  type: NodePort