apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: lutovp/test-frontend:0.0.7
          imagePullPolicy: IfNotPresent
          name: frontend
          ports:
            - containerPort: 80       
