
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: prod
spec:
  ports:
    - name: web
      port: 8000
      targetPort: 80
      nodePort: 30080     
  selector:
    app: frontend
  type: NodePort
