apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configuration
  namespace: stage  
  labels:
    app: postgres
data:
  POSTGRES_DB: news
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres