apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.db.statefulSetName }}  
  namespace: {{ .Values.namespace }}  
  labels:
    app: postgres
spec:
  serviceName: "postgres"
  replicas:  {{ .Values.db.replicaCount }}
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: {{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}
        envFrom:
        - configMapRef:
            name: {{ .Values.configMap.name }} 
        ports:
        - containerPort: {{.Values.db.port }}
          name: postgresdb
