apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.serviceName }} 
  namespace: {{ .Values.namespace }}  
  labels:
    app: postgres
spec:
  ports:
  - port: {{ .Values.db.port }}
    name: postgres
  type: ClusterIP 
  selector:
    app: postgres