apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.back.serviceName }}
  namespace: {{ .Values.namespace }}  
spec:
  ports:
    - name: web
      port:  {{ .Values.back.port }}
      targetPort:  {{ .Values.back.port }}  
      nodePort:  {{ .Values.back.nodePort }}            
  selector:
    app: backend
  type: NodePort