
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.front.serviceName }}
  namespace: {{ .Values.namespace }}  
spec:
  ports:
    - name: web
      port: {{ .Values.front.port }} 
      targetPort: {{ .Values.front.targetPort }}      
      nodePort:  {{ .Values.front.nodePort }}      
  selector:
    app: frontend
  type: NodePort
