apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: stage
spec:
  ports:
    - name: web
      port: 8000
      targetPort: 80
      protocol: TCP      
      nodePort: 30080      
  selector:
    app: news
  type: NodePort
