apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: stage
spec:
  ports:
    - name: web
      port: 9000
      targetPort: 9000
      protocol: TCP      
      nodePort: 30090            
  selector:
    app: news
  type: NodePort