apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: prod
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: postgres
    nodePort: 30433
  type: NodePort 
  selector:
    app: postgres